name: Builds Artifact and Release

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: EFI

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      JOB_TYPE: BUILD

    steps:
    - uses: actions/checkout@v4.2.1
      
    - name: Zip EFI
      run: |
        rm -Rf TOOLS
        rm -Rf "Bios  V 1.49 SysReport"
        rm -Rf Screenshot
        rm -Rf "X1 Tablet 3°Gen.ioreg"
        rm -Rf README.md
        rm -Rf opencore-2024-01-10-205829.txt
        rm -Rf .gitignore       
        rm -Rf ".github"
        rm -Rf ".git"
        
        zip -r Lenovo_ThinkPad_X1-Tablet_Gen3.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Lenovo_ThinkPad_X1-Tablet_Gen3
        path: Lenovo_ThinkPad_X1-Tablet_Gen3.zip

    - name: Upload build
      uses: svenstaro/upload-release-action@2.9.0
      if: github.event_name != 'pull_request'
      with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: ./*.zip
         tag: ${{ github.ref }}
         release_name: EFI ThinkPad X1Tablet Gen3 Hackintosh
         body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
         file_glob: true
         overwrite: true
